apiVersion: apps/v1
kind: Deployment
metadata:
  name: adminer-deployment
  labels:
    app: adminer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adminer
  template:
    metadata:
      labels:
        app: adminer
    spec:
      containers:
      - name: adminer
        # Imagem oficial do Adminer.
        image: adminer
        # Variáveis de ambiente para o contêiner do Adminer.
        env:
        - name: ADMINER_DEFAULT_SERVER
          # Define o servidor padrão para o Adminer se conectar.
          # Usamos o nome do serviço do MySQL, que o DNS do Kubernetes
          # resolverá para o IP interno do serviço.
          value: mysql-service
        ports:
        - containerPort: 8080 # Adminer escuta na porta 8080.
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "250m"
        # Sondas de saúde para o Adminer.
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10